//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<flowingtime:timewatch>);
recipes.remove(<flowingtime:flpedestal>);
//Don't touch me!
//#Add
// Pedestal
mods.avaritia.ExtremeCrafting.addShaped("Pedestal", <flowingtime:flpedestal> * 1, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, null],[null, null, null, <avaritia:block_resource:0>, <mekanismecoenergistics:controlcircuitavaritia:1>, <avaritia:block_resource:0>, null, null, null],[null, null, null, <avaritia:block_resource:0>, <mekanismecoenergistics:controlcircuitavaritia:1>, <avaritia:block_resource:0>, null, null, null],[null, null, null, <avaritia:block_resource:0>, <mekanismecoenergistics:controlcircuitavaritia:1>, <avaritia:block_resource:0>, null, null, null],[null, null, null, <avaritia:block_resource:0>, <mekanismecoenergistics:controlcircuitavaritia:1>, <avaritia:block_resource:0>, null, null, null],[<avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia:block_resource:0>]]);
// Time Watch
mods.avaritia.ExtremeCrafting.addShaped("Time Watch", <flowingtime:timewatch> * 1, [[null, null, null, null, null, null, null, null, null], [null, <divinerpg:arksiane_disk>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <divinerpg:arksiane_disk>, null],[null, <iuadditions:iridium_advanced_stellar>, <industrialupgrade:quarrymodules:5>, <industrialupgrade:modultype:5>, <extrabotany:buddhistrelics>, <industrialupgrade:modultype:4>, <industrialupgrade:quarrymodules:5>, <iuadditions:iridium_advanced_stellar>, null],[null, <iuadditions:iridium_advanced_stellar>, <jaopca:avaritia_singularity.cosmic_neutronium>, <mekanism:cosmicmatter>, <botania:gaiahead>, <mekanism:cosmicmatter>, <jaopca:avaritia_singularity.cosmic_neutronium>, <iuadditions:iridium_advanced_stellar>, null],[null, <iuadditions:iridium_advanced_stellar>, <iuadditions:core_crossdimensional>, <botania:gaiahead>, <draconicadditions:chaos_crystal_stable>, <botania:gaiahead>, <iuadditions:core_crossdimensional>, <iuadditions:iridium_advanced_stellar>, null],[null, <iuadditions:iridium_advanced_stellar>, <jaopca:avaritia_singularity.cosmic_neutronium>, <mekanism:cosmicmatter>, <botania:gaiahead>, <mekanism:cosmicmatter>, <jaopca:avaritia_singularity.cosmic_neutronium>, <iuadditions:iridium_advanced_stellar>, null],[null, <iuadditions:iridium_advanced_stellar>, <industrialupgrade:quarrymodules:5>, <industrialupgrade:modultype:4>, <botania:hourglass>, <industrialupgrade:modultype:5>, <industrialupgrade:quarrymodules:5>, <iuadditions:iridium_advanced_stellar>, null],[null, <divinerpg:arksiane_disk>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <iuadditions:iridium_advanced_stellar>, <divinerpg:arksiane_disk>, null],[null, null, null, null, null, null, null, null, null]]);
#reloadable
//File End
