#reloadable
import crafttweaker.item.IItemStack;
import crafttweaker.liquid.ILiquidStack;
import mods.mekanism.enrichment;
import mods.mekanism.crusher;
import mods.mekanism.compressor;
//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
//recipes.remove(AAAA);

val itemsToRemove = [
  
]as IItemStack[];
for item in itemsToRemove {
  recipes.remove(item);
}

recipes.addShapeless(<mekanism:otherdust:1>, [<thermalfoundation:material:96>]);

recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 9}), [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:morealloy:9>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}).onlyWithTag({tier: 8})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 8}) * 2, [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:morealloy:8>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}).onlyWithTag({tier: 7})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 7}) * 2, [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:morealloy:7>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}).onlyWithTag({tier: 6})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 6}) * 2, [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:morealloy:5>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}).onlyWithTag({tier: 4})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 4}) * 2, [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:morealloy:4>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}).onlyWithTag({tier: 3})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 3}) * 4, [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:morealloy:3>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}).onlyWithTag({tier: 2})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 2}) * 4, [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:morealloy:2>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}).onlyWithTag({tier: 1})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 1}) * 4, [[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0})],[<mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:morealloy:1>, <mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0})], [<mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}).onlyWithTag({tier: 0})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter>.withTag({tier: 0}) * 4, [[<mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3})],[<mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:morealloy>, <mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3})], [<mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter>.withTag({tier: 3}).onlyWithTag({tier: 3})]]);

recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 9}), [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:morealloy:9>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}).onlyWithTag({tier: 8})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 8}), [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:morealloy:8>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}).onlyWithTag({tier: 7})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 7}), [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:morealloy:7>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}).onlyWithTag({tier: 6})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 6}), [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:morealloy:6>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}).onlyWithTag({tier: 5})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 5}) * 2, [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:morealloy:5>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}).onlyWithTag({tier: 4})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 4}) * 2, [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:morealloy:4>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 3}) * 4, [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:morealloy:3>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}).onlyWithTag({tier: 2})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 2}) * 4, [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:morealloy:2>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}).onlyWithTag({tier: 1})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 1}) * 4, [[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0})],[<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:morealloy:1>, <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0})], [<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}).onlyWithTag({tier: 0})]]);

recipes.addShaped(<mekanismecoenergistics:ecotransmitter:2>.withTag({tier: 0}) * 4, [[<mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3})],[<mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:morealloy>, <mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3})], [<mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}).onlyWithTag({tier: 3})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 9}), [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:morealloy:9>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}).onlyWithTag({tier: 8})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 8}), [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:morealloy:8>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}).onlyWithTag({tier: 7})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 7}), [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:morealloy:7>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}).onlyWithTag({tier: 6})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 6}), [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:morealloy:6>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}).onlyWithTag({tier: 5})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 5}), [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:morealloy:5>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}).onlyWithTag({tier: 4})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 4}) * 2, [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:morealloy:4>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 3}) * 2, [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:morealloy:3>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}).onlyWithTag({tier: 2})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 2}) * 4, [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:morealloy:2>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}).onlyWithTag({tier: 1})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 1}) * 4, [[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0})],[<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:morealloy:1>, <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0})], [<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0}), <mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}).onlyWithTag({tier: 0})]]);
recipes.addShaped(<mekanismecoenergistics:ecotransmitter:1>.withTag({tier: 0}) * 4, [[<mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3})],[<mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanismecoenergistics:morealloy>, <mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3})], [<mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3}), <mekanism:transmitter:1>.withTag({tier: 3}).onlyWithTag({tier: 3})]]);

enrichment.removeRecipe(<ore:dustLapis>, <minecraft:dye:4>);
enrichment.removeRecipe(<ore:dustEmerald>, <minecraft:emerald>);
//enrichment.addRecipe(llngredient, IltemStack);
enrichment.addRecipe(<jaopca:dust.cosmic_neutronium>, <mekanismecoenergistics:compressedavaritia:1>);

enrichment.addRecipe(<industrialupgrade:itemdust:25>, <mekanismecoenergistics:morecompressed:3>);
enrichment.addRecipe(<mekanism:dust:7>, <mekanismecoenergistics:morecompressed:5>);
enrichment.addRecipe(<industrialupgrade:itemdust:78>, <mekanismecoenergistics:morecompressed:5>);
enrichment.addRecipe(<industrialupgrade:itemdust:27>, <mekanismecoenergistics:morecompressed>);

enrichment.addRecipe(<industrialupgrade:itemdust:74>, <mekanismecoenergistics:morecompressed:1>);
enrichment.addRecipe(<jaopca:dust.emerald>, <mekanismecoenergistics:morecompressed:1>);
enrichment.addRecipe(<industrialupgrade:itemdust:17>, <mekanismecoenergistics:morecompressed:6>);

enrichment.addRecipe(<industrialupgrade:itemdust:10>, <mekanismecoenergistics:morecompressed:4>);
//crusher.addRecipe(llngredient, IltemStack):
crusher.addRecipe(<mekanismecoenergistics:moreingot>, <mekanismecoenergistics:moredust:2>);


//compressor.addRecipe(llngredient, IGasStack, IltemStack);

compressor.addRecipe(<industrialupgrade:itemdust:27>,<mekanismecoenergistics:morecompressed>);



//File End
